# Generated by Django 5.2.1 on 2025-05-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text='Clase CSS para el ícono', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['name'],
            },
        ),
    ]
