# Generated by Django 5.2.1 on 2025-05-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generos', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date'], 'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=90, help_text='Duración en minutos'),
        ),
        migrations.AddField(
            model_name='movie',
            name='generos',
            field=models.ManyToManyField(related_name='movies', to='generos.genero'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
